services:
    shf_api.event.page_request_listener:
        class: App\Event\Listener\PageRequestListener
        arguments: ['@security.token_storage', '@router']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    shf_api.event.jwt_created_listener:
        class: App\Event\Listener\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    shf_api.event.jwt_decoded_listener:
        class: App\Event\Listener\JWTDecodedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }