login:
    path: /login
    methods: [GET|POST]
    controller: App\Controller\Visitor\PageVisitorController::login

visitor_index:
    path: /
    methods: [GET]
    controller: App\Controller\Visitor\PageVisitorController::index

visitor_register:
    path: /register
    methods: [GET|POST]
    controller: App\Controller\Visitor\PageVisitorController::register