api_user_mission_list:
    path: /api/user-missions
    controller: App\Controller\Api\User\UserMissionApiController::getMany
    methods: GET

api_user_mission_get:
    path: /api/user-missions/{id}
    controller: App\Controller\Api\User\UserMissionApiController::getOne
    methods: GET
    requirements:
        id: \d+

api_user_mission_post:
    path: /api/user-missions
    controller: App\Controller\Api\User\UserMissionApiController::post
    methods: POST

api_user_mission_put:
    path: /api/user-missions/{id}
    controller: App\Controller\Api\User\UserMissionApiController::put
    methods: PUT
    requirements:
        id: \d+

api_user_mission_delete:
    path: /api/user-missions/{id}
    controller: App\Controller\Api\User\UserMissionApiController::delete
    methods: DELETE
    requirements:
        id: \d+

api_user_mission_patch:
    path: /api/user-missions/{action}
    controller: App\Controller\Api\User\UserMissionApiController::patch
    methods: PATCH
    requirements:
        action: complete