api_water_tracker_entry_list:
    path: /api/water-trackers/{trackerId}/entries
    controller: App\Controller\Api\WaterTrackerEntryApiController::getMany
    methods: GET

api_water_tracker_entry_get:
    path: /api/water-trackers/{trackerId}/entries/{id}
    controller: App\Controller\Api\WaterTrackerEntryApiController::getOne
    methods: GET

api_water_tracker_entry_post:
    path: /api/water-trackers/{trackerId}/entries
    controller: App\Controller\Api\WaterTrackerEntryApiController::post
    methods: POST

api_water_tracker_entry_put:
    path: /api/water-trackers/{trackerId}/entries/{id}
    controller: App\Controller\Api\WaterTrackerEntryApiController::put
    methods: PUT

api_water_tracker_entry_delete:
    path: /api/water-trackers/{trackerId}/entries/{id}
    controller: App\Controller\Api\WaterTrackerEntryApiController::delete
    methods: DELETE


front_api_water_tracker_entry_post:
    path: /front/api/water-trackers/{trackerId}/entries
    controller: App\Controller\Front\WaterTrackerEntryProxyController::post
    methods: POST

front_api_water_tracker_entry_put:
    path: /front/api/water-trackers/{trackerId}/entries/{id}
    controller: App\Controller\Front\WaterTrackerEntryProxyController::put
    methods: PUT

front_api_water_tracker_entry_delete:
    path: /front/api/water-trackers/{trackerId}/entries/{id}
    controller: App\Controller\Front\WaterTrackerEntryProxyController::delete
    methods: DELETE

