api_workout_list:
    path: /api/workouts
    controller: App\Controller\Api\WorkoutApiController::getMany
    methods: GET

api_workout_get:
    path: /api/workouts/{id}
    controller: App\Controller\Api\WorkoutApiController::getOne
    methods: GET
    requirements:
        id: \d+

api_workout_post:
    path: /api/workouts
    controller: App\Controller\Api\WorkoutApiController::post
    methods: POST

api_workout_post_with_type:
    path: /api/workouts/{workoutType}
    controller: App\Controller\Api\WorkoutApiController::postWithType
    methods: POST
    requirements:
        workoutType: reference|personal

api_workout_put:
    path: /api/workouts/{id}
    controller: App\Controller\Api\WorkoutApiController::put
    methods: PUT
    requirements:
        id: \d+

api_workout_delete:
    path: /api/workouts/{id}
    controller: App\Controller\Api\WorkoutApiController::delete
    methods: DELETE
    requirements:
        id: \d+

api_workout_patch:
    path: /api/workouts/{action}
    controller: App\Controller\Api\WorkoutApiController::patch
    methods: PATCH
    requirements:
        action: complete|undo-complete



front_api_workout_list_reference:
    path: /front/api/reference/workouts
    controller: App\Controller\Front\WorkoutProxyController::getManyReference
    methods: GET

front_api_workout_list_personal:
    path: /front/api/personal/workouts
    controller: App\Controller\Front\WorkoutProxyController::getManyPersonal
    methods: GET

front_api_workout_get:
    path: /front/api/workouts/{id}
    controller: App\Controller\Front\WorkoutProxyController::getOne
    methods: GET
    requirements:
        id: \d+

front_api_workout_post_with_type:
    path: /api/workouts/{workoutType}
    controller: App\Controller\Api\WorkoutProxyController::postWithType
    methods: POST
    requirements:
        workoutType: reference|personal

front_api_workout_patch:
    path: /front/api/workouts/{action}
    controller: App\Controller\Front\WorkoutProxyController::patch
    methods: PATCH
    requirements:
        action: complete|undo-complete