api_workout_step_list:
    path: /api/workouts/{workoutId}/steps
    controller: App\Controller\Api\WorkoutStepApiController::getMany
    methods: GET

api_workout_step_get:
    path: /api/workouts/{workoutId}/steps/{id}
    controller: App\Controller\Api\WorkoutStepApiController::getOne
    methods: GET

api_workout_step_post:
    path: /api/workouts/{workoutId}/steps
    controller: App\Controller\Api\WorkoutStepApiController::post
    methods: POST

api_workout_step_put:
    path: /api/workouts/{workoutId}/steps/{id}
    controller: App\Controller\Api\WorkoutStepApiController::put
    methods: PUT

api_workout_step_delete:
    path: /api/workouts/{workoutId}/steps/{id}
    controller: App\Controller\Api\WorkoutStepApiController::delete
    methods: DELETE


front_api_workout_step_get_many:
    path: /front/api/workouts/{workoutId}/steps
    controller: App\Controller\Front\WorkoutStepProxyController::getMany
    methods: GET

front_api_workout_step_delete:
    path: /front/api/workouts/{workoutId}/steps/{id}
    controller: App\Controller\Front\WorkoutStepProxyController::delete
    methods: GET