configuration:
    subject: 'email.NAME_OF_EMAIL.subject'
    sender:
        name: 'Super Hero Factory'
        email: 'notification@superherofactory.com'
    optin: ~
    template: 'NAME_OF_EMAIL.html.twig'
