App\Entity\Workout\AbstractWorkoutStep:
    properties:
        position:
            - NotNull: ~
            - Type: integer
        exercise:
            - NotNull: ~
            - Type: App\Entity\Workout\Exercise