App\Entity\Workout\AbstractWorkout:
    properties:
        name:
            - NotBlank: ~
            - Regex:
                pattern: '/^[a-zA-Z0-9_ ]*$/'
                message: Ne peux pas contenir de caractères spéciaux
            - Length:
                max: 150
        source:
            - NotBlank: ~
            - Choice: ['shf', 'community']
