App\Entity\AbstractWorkout:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 150
        source:
            - NotBlank: ~
            - Choice: ['shf', 'community']
