App\Entity\User\UserBodyMeasurement:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [user]

    properties:
        height:
            - Range:
                min: 100
                max: 270
        weight:
            - Range:
                min: 40000
                max: 500000
                minMessage: Value must be between 40kg and 500kg
                maxMessage: Value must be between 40kg and 500kg
        restingHeartRate:
            - Range:
                min: 20
                max: 150