App\Entity\User\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]

    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 5
                max: 15
        email:
            - NotBlank: ~
            - Email:
        password:
            - NotBlank: ~