App\Entity\User\UserFavoriteWorkout:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [user, workout]

    properties:
        user:
            - NotNull: ~
            - Type: App\Entity\User\User
        workout:
            - NotNull: ~
            - Type: App\Entity\Workout\ReferenceWorkout

