App\Entity\User\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]

    properties:
        username:
            - NotBlank: ~
            - Type: alnum
            - Length:
                min: 4
                max: 15
        email:
            - NotBlank: ~
            - Email:
        password:
            - NotBlank:
                groups: [registration]
            - Regex:
                pattern: '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/'
                message: Doit contenir 8 caractères avec au moins une majuscule, une minuscule et un chiffre
                groups: [registration]
