App\Entity\AbstractWorkout:
    type: entity
    table: "`workout`"
    repositoryClass: App\Repository\WorkoutRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: source
        type: string
    discriminatorMap:
        shf: App\Entity\ShfWorkout
        community: App\Entity\CommunityWorkout

    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        name:
            column: name
            type: string
            length: 255
            unique: true
            nullable: false
        difficulty:
            column: difficulty
            type: integer
            unique: false
            nullable: true
        duration:
            column: duration
            type: integer
            unique: false
            nullable: true
        calories:
            column: calories
            type: integer
            unique: false
            nullable: true
        experience:
            column: experience
            type: integer
            unique: false
            nullable: true