App\Entity\AbstractWorkout:
    type: entity
    table: "`workout`"
    indexes:
        source_index:
          columns: [ source ]
    repositoryClass: App\Repository\WorkoutRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        reference: App\Entity\ReferenceWorkout
        personal: App\Entity\PersonalWorkout

    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        name:
            column: name
            type: string
            length: 255
            unique: false
            nullable: false
        difficulty:
            column: difficulty
            type: integer
            unique: false
            nullable: true
        estimatedDuration:
            column: estimated_duration
            type: integer
            unique: false
            nullable: true
        calories:
            column: calories
            type: integer
            unique: false
            nullable: true
        experience:
            column: experience
            type: integer
            unique: false
            nullable: true
        source:
            column: source
            unique: false
            nullable: false

    manyToOne:
        creator:
            targetEntity: App\Entity\User
            nullable: false
            joinColumn:
                name: creator_id
                referencedColumnName: id
