App\Entity\User\UserBodyMeasurement:
    type: entity
    table: "`user_body_measurement`"
    repositoryClass: App\Repository\User\UserBodyMeasurementRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    oneToOne:
        user:
            targetEntity: App\Entity\User\User
            nullable: false
            unique: true
            joinColumn:
                name: user_id
                referencedColumnName: id
                cascade: ['delete']
