App\Entity\User\UserBodyMeasurementHistory:
    type: entity
    table: "`user_body_measurement_history`"
    repositoryClass: App\Repository\User\UserBodyMeasurementHistoryRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    manyToOne:
        user:
            targetEntity: App\Entity\User\User
            nullable: false
            unique: false
            joinColumn:
                name: user_id
                referencedColumnName: id
                cascade: ['delete']
