App\Entity\UserBodyMeasurement:
    type: entity
    table: "`user_body_measurement`"
    repositoryClass: App\Repository\UserBodyMeasurementRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        height:
            column: height
            type: integer
            unique: false
            nullable: true
        weight:
            column: weight
            type: integer
            unique: false
            nullable: true
        restingHeartRate:
            column: resting_heart_rate
            type: integer
            unique: false
            nullable: true

    oneToOne:
        user:
            targetEntity: App\Entity\User
            inversedBy: bodyMeasurement
            nullable: false
            unique: true
            joinColumn:
                name: user_id
                referencedColumnName: id
                cascade: ['delete']
