App\Entity\UserWorkout:
    type: entity
    table: "`user_workout`"
    repositoryClass: App\Repository\UserWorkoutRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        scheduledDate:
            column: scheduled_date
            type: datetime
            unique: false
            nullable: true
        completionDate:
            column: completion_date
            type: datetime
            unique: false
            nullable: true

    manyToOne:
        workout:
            targetEntity: App\Entity\AbstractWorkout
            nullable: false
            joinColumn:
                name: workout_id
                referencedColumnName: id

        user:
            targetEntity: App\Entity\User
            nullable: false
            joinColumn:
                name: user_id
                referencedColumnName: id
