App\Entity\User\User:
    type: entity
    table: "`user`"
    indexes:
        user_username_index:
          columns: [ username ]
    repositoryClass: App\Repository\User\UserRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        username:
            column: username
            type: string
            unique: true
            nullable: false
            length: 150
        email:
            column: email
            type: string
            unique: true
            nullable: false
            length: 150
        password:
            column: password
            type: string
            length: 255
            unique: false
            nullable: false
        isAdmin:
            column: is_admin
            type: boolean
            unique: false
            nullable: false
        confirmationKey:
            column: confirmation_key
            type: string
            unique: true
            nullable: true
        confirmationKeyExpiration:
            column: confirmation_key_expiration
            type: datetime
            unique: false
            nullable: true
        roles:
            column: roles
            type: array
            unique: false
            nullable: false
        lastLogin:
            column: last_login
            type: datetime
            unique: false
            nullable: true

    oneToOne:
        character:
            column: character_id
            targetEntity: App\Entity\Character\Character
            mappedBy: user
            nullable: true
            unique: true
