App\Entity\WaterTracker\WaterTracker:
    type: entity
    table: "`water_tracker`"
    indexes:
        user_index:
          columns: [ user_id ]
    repositoryClass: App\Repository\WaterTracker\WaterTrackerRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        target:
            column: target
            type: integer
            nullable: false
            unique: false

    oneToMany:
        entries:
            targetEntity: App\Entity\WaterTracker\WaterTrackerEntry
            mappedBy: tracker
            cascade: ['persist']

    manyToOne:
        user:
            targetEntity: App\Entity\User\User
            joinColumn:
                name: user_id
                referencedColumnName: id