App\Entity\WaterTracker:
    type: entity
    table: "`water_tracker`"
    repositoryClass: App\Repository\WaterTrackerRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        target:
            type: integer
            nullable: false
            unique: false

    oneToMany:
        entries:
            targetEntity: App\Entity\WaterTrackerEntry
            mappedBy: tracker
            cascade: ['persist']

    manyToOne:
        user:
            targetEntity: App\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id