App\Entity\WorkoutRepsStep:
    type: entity
    fields:
        numberOfRepetition:
            column: number_of_repetition
            type: integer
            nullable: false
            unique: false