App\Entity\Workout\Exercise:
    type: entity
    table: "`exercise`"
    repositoryClass: App\Repository\Workout\ExerciseRepository

    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY

    fields:
        name:
            column: name
            type: string
            length: 255
            unique: true
            nullable: false
        type:
            column: type
            type: string
            length: 25
            unique: false
            nullable: false

    manyToMany:
        equipments:
            targetEntity: App\Entity\Workout\Equipment
            joinTable:
                name: exercise_has_equipment
                joinColumns:
                    exercise_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    equipment_id:
                        referencedColumnName: id