App\Entity\Workout\WorkoutAmrapStep:
    type: entity
    fields:
        duration:
            column: duration
            type: integer
            nullable: false
            unique: false
        repsDone:
            column: reps_done
            type: integer
            nullable: false
            unique: false