App\Entity\Workout\PersonalWorkout:
    type: entity
    repositoryClass: App\Repository\Workout\PersonalWorkoutRepository

    fields:
        scheduledDate:
            name: scheduled_date
            type:  datetime
            unique: false
            nullable: true
        completionDate:
            name: completion_date
            type:  datetime
            unique: false
            nullable: true

    manyToOne:
        owner:
            targetEntity: App\Entity\User\User
            nullable: false
            joinColumn:
                name: owner_id
                referencedColumnName: id
        referenceWorkout:
            targetEntity: App\Entity\Workout\ReferenceWorkout
            nullable: false
            joinColumn:
                name: reference_id
                referencedColumnName: id
