App\Entity\Workout\AbstractWorkoutStep:
    type: entity
    table: "`workout_step`"
    repositoryClass: App\Repository\Workout\WorkoutStepRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: source
        type: string
    discriminatorMap:
        amrap: App\Entity\Workout\WorkoutAmrapStep
        distance: App\Entity\Workout\WorkoutDistanceStep
        duration: App\Entity\Workout\WorkoutDurationStep
        reps: App\Entity\Workout\WorkoutRepsStep
        rest: App\Entity\Workout\WorkoutRestStep

    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        position:
            column: position
            type: integer
            unique: false
            nullable: false
        estimatedDuration:
            column: estimated_duration
            type: integer
            unique: false
            nullable: true

    manyToOne:
            workout:
                targetEntity: App\Entity\Workout\AbstractWorkout
                joinColumn:
                    name: workout_id
                    referencedColumnName: id
            exercise:
                targetEntity: App\Entity\Workout\Exercise
                joinColumn:
                    name: exercise_id
                    referencedColumnName: id